name = "Streamator"
mainprefix = "tc"
modname = "Streamator"
prefix = ""
author = "Streamator Team"
sig_version = 3
version = "0.0.0" # NB: this is not the real version number. We use git tags.
reuse_private_key = false
files = [
    "mod.cpp",
    "*.paa",
    "LICENSE"
]
include = ["./include"]

releasebuild = [
    "@zip @Streamator"
]

[header_exts]
version= "{{git \"id 8\"}}"
