name = "Streamator"
mainprefix = "tc"
modname = "Streamator"
prefix = ""
author = "Streamator Team"
sig_version = 3
version = "0.3.0.291"
reuse_private_key = false
files = [
    "mod.cpp",
    "*.paa",
    "LICENSE"
]
include = ["./include"]

check = [
    "!version_set"
]

postbuild = [
    "!version_unset"
]

releasebuild = [
    "@zip @Streamator"
]

key_name = "Streamator_{{version}}"
authority = "Streamator_{{version}}-{{git \"id 8\"}}"

[header_exts]
version= "{{git \"id 8\"}}"

[scripts.version_set]
steps_linux = [
    "echo 'Setting version'",
    "sed -i -r -s 's/#define MAJOR 0/#define MAJOR {{semver.major}}/g' addons/Streamator/macros.hpp",
    "sed -i -r -s 's/#define MINOR 0/#define MINOR {{semver.minor}}/g' addons/Streamator/macros.hpp",
    "sed -i -r -s 's/#define PATCHLVL 0/#define PATCHLVL {{semver.patch}}/g' addons/Streamator/macros.hpp",
    "sed -i -r -s 's/#define BUILD 0/#define PATCHLVL {{semver.build}}/g' addons/Streamator/macros.hpp",
]
steps_windows = [
    "echo 'Setting version'",
    "powershell -Command foreach ($f in 'addons/Streamator/macros.hpp') {(Get-Content $f) -replace '#define MAJOR 0', '#define MAJOR {{semver.major}}' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/Streamator/macros.hpp') {(Get-Content $f) -replace '#define MINOR 0', '#define MINOR {{semver.minor}}' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/Streamator/macros.hpp') {(Get-Content $f) -replace '#define PATCHLVL 0', '#define PATCHLVL {{semver.patch}}' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/Streamator/macros.hpp') {(Get-Content $f) -replace '#define BUILD 0', '#define PATCHLVL {{semver.build}}' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
]

only_release = true
show_output = true

[scripts.version_unset]
steps_linux = [
    "echo 'Unsetting version'",
    "sed -i -r -s 's/#define MAJOR {{semver.major}}/#define MAJOR 0/g' addons/Streamator/macros.hpp",
    "sed -i -r -s 's/#define MINOR {{semver.minor}}/#define MINOR 0/g' addons/Streamator/macros.hpp",
    "sed -i -r -s 's/#define PATCHLVL {{semver.patch}}/#define PATCHLVL 0/g' addons/Streamator/macros.hpp",
    "sed -i -r -s 's/#define PATCHLVL {{semver.build}}/#define BUILD 0/g' addons/Streamator/macros.hpp",
]
steps_windows = [
    "echo 'Unsetting version'",
    "powershell -Command foreach ($f in 'addons/Streamator/macros.hpp') {(Get-Content $f) -replace '#define MAJOR {{semver.major}}', '#define MAJOR 0' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/Streamator/macros.hpp') {(Get-Content $f) -replace '#define MINOR {{semver.minor}}', '#define MINOR 0' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/Streamator/macros.hpp') {(Get-Content $f) -replace '#define PATCHLVL {{semver.patch}}', '#define PATCHLVL 0' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
    "powershell -Command foreach ($f in 'addons/Streamator/macros.hpp') {(Get-Content $f) -replace '#define PATCHLVL {{semver.build}}', '#define BUILD 0' -join \"`n\" ^| Set-Content -NoNewline $f; Add-Content -NoNewline \"`n\" $f}",
]

only_release = true
show_output = true
